### ISSUE TITLE
Improve Mobile Experience for Main Screen and Objective View

### ISSUE THREAD

**Issue by SephHawkins** [ti-assistant/issues#1]
Currently the Main Screen and Objective View don't properly show up on mobile devices.

They should be restructured to be at least usable - though some information will likely need to be removed or hidden to get things to work properly.

**Comment by signoreliro** [comment]
On mobile when setting up the game, going into 'options' and clicking either 'other' OR 14 enables both 'other' and 14 victory points.

**Comment by SephHawkins** [comment]
> On mobile when setting up the game, going into 'options' and clicking either 'other' OR 14 enables both 'other' and 14 victory points.

This is fixed on staging. Leaving this open until the main screen is usable on mobile.
