### ISSUE TITLE
Ability to rotate hyperlane tiles

### ISSUE THREAD

**Issue by GabeHeath** [ti-assistant/issues#27]
Perhaps this feature already exists, but I was unable to find a solution.

I have this 8 player map string which was generated by a Milty draft at https://milty.shenanigans.be/
```
87A1 89B3 33 87A4 89B0 44 39 69 23 34 61 37 73 76 35 20 70 45 72 30 43 66 40 83B2 21 50 75 22 42 77 25 41 83B2 64 60 29 6 49 46 2 0 0 7 78 0 57 48 80 15 28 47 55 0 0 16 74 0 17 68 24

```

In this generated string, It appears that the hyperlane tiles have an extra number at the end to indicate their clockwise rotation. When I enter this string into this application the hyperlane tiles are broken images because, I assume, they can't account for the rotation.

<img width="918" alt="Screenshot 2023-11-17 at 11 53 28 AM" src="https://github.com/ti-assistant/issues/assets/2744074/bd35b144-eaf6-41ad-8ecd-e048ed866c78">

**Comment by SephHawkins** [comment]
Interesting. That's definitely the case, it doesn't handle the extra character at the end - I'll see about fixing that (and fixing the grayed out tiles on the edge).

During game setup, it's possible to change the map type to "Warp", which should automatically put the hyper-lanes in the right location, but once the game is created, there's not a way to edit that. I've created #28 to track and fix that.

<img width="960" alt="image" src="https://github.com/ti-assistant/issues/assets/3288953/57d535c2-047c-43f9-90c9-08b8bd2d4672">

**Comment by SephHawkins** [comment]
This is now fixed. Any hyperlane tiles with the added rotation number should correctly rotate instead of being invalid and any "-1" tiles will not be displayed.
