### ISSUE TITLE
Improve Techs, Objectives and Planets views

### ISSUE THREAD

**Issue by Yan-rlathotep** [ti-assistant/issues#3]
Hi!

**Short version**: I suggest replacing the view of Techs, Objectives and Planets on Main Screen with that of Add Planets from faction screens to improve both the tablet and laptop experience

Your tool looks great on a big screen, and I understand it's challenging to display on a mobile. On tablets it just needs a little fix

I feel like my tablet (iPad Air with Safari, used in landscape position) would be the perfect interface to update game data during play, and it certainly is big enough to hold all the info. The only issue is that the Techs, Objectives and Planets buttons on the Main Screen open downward, out of boundaries, instead of covering the screen

![B10ABAE3-2C83-4CBB-A199-0A46A807CF87](https://user-images.githubusercontent.com/36864061/235436111-983eb446-c682-4655-9b55-a1ce04d3b6b7.jpeg)

You did that very well with the "Add Planet" button in the faction window. It opens a scrollable view with a little cross to close it. I would suggest using the same for Techs, Objectives and Planets.

Even on laptop, I find those three buttons rather unintuitive, e.g. if I hover on Techs by mistake when trying to reach Objectives, I have to move my mouse a lot to just close the popup and try again. Why not just click on them? Or at least keep displaying all three of them so I can still reach Objectives after opening Techs?

Thanks for the hard work, I really appreciate it, having developed homemade tools (with React) for my own TI4 games

**Comment by SephHawkins** [comment]
Thanks for this feedback - and for providing the screenshot! It's super helpful for debugging.

> I feel like my tablet (iPad Air with Safari, used in landscape position) would be the perfect interface to update game data during play, and it certainly is big enough to hold all the info. The only issue is that the Techs, Objectives and Planets buttons on the Main Screen open downward, out of boundaries, instead of covering the screen

You're right, this is definitely an issue. They open downward when there isn't enough room above them, but their size should be based on screen size so they should always fit. 

> You did that very well with the "Add Planet" button in the faction window. It opens a scrollable view with a little cross to close it. I would suggest using the same for Techs, Objectives and Planets.
> 
> Even on laptop, I find those three buttons rather unintuitive, e.g. if I hover on Techs by mistake when trying to reach Objectives, I have to move my mouse a lot to just close the popup and try again. Why not just click on them? Or at least keep displaying all three of them so I can still reach Objectives after opening Techs?

That's reasonable - the reason I went with the "hover" option was to try to minimize the number of button presses required, but in the case of those three, there's a strong argument to be made that trying to move to just the right one is more annoying than the extra click to open and close it. Displaying all three of them was something I tried, but ran into issues trying to get them to display correctly when there were popups on the screen as well (e.g. a tech info popup).

> Thanks for the hard work, I really appreciate it, having developed homemade tools (with React) for my own TI4 games

You're welcome! My hope is that it'll help people's games run more smoothly!

Also, in the screenshot, it looks like things are overflowing the sides - I'll create a separate bug for that and see about fixing it.

**Comment by SephHawkins** [comment]
Alright - this should now be resolved on staging. I ended up overhauling all of the three so that they work at all screen sizes.

I've got a couple more issues to resolve on the current staging build, and then I'll go ahead and push it to prod.
