### ISSUE TITLE
Client Error Issue

### ISSUE THREAD

**Issue by willcarey119** [ti-assistant/issues#34]
Experienced a client side issue during our game yesterday. Unsure about the cause. 

https://ti-assistant.com/game/V3yByF/main

**Comment by Yoduh** [comment]
I was able to reproduce by simply having **Imperial Arbiter** law active at the end of the strategy phase.  The error immediately occurs the moment the last player selects a strategy card.

It is [Minified React error #185](https://react.dev/errors/185?invariant=185)

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by willcarey119** [comment]
Confirming that I run into the same issue when enabling Hacan's Quantum Datahub Node, so it's probably a wider issue relating to things that add interactions into the end of the strategy phase.

**Comment by sharpchris** [comment]
I also had the same bug with Imperial Arbiter in play.

**Comment by SephHawkins** [comment]
Thank you for reporting this - and for the detailed debugging information. I'll try to get this resolved today.

**Comment by SephHawkins** [comment]
This should now be fixed - ended up being an issue with trying to repeatedly auto-select the strategy card to swap when there was only 1 available (5, 6, 7, and 8 player games).
