### ISSUE TITLE
New Strings needing translation

### ISSUE THREAD

**Issue by SephHawkins** [ti-assistant/issues#35]
Added some strings as a result of a recent PR.

- [x] Base Game (id: 2fB0Ox)
- [x] Map Builder (id: OAXWRP)
- [x] Hyperspace (id: i4Uu4m)

If there's a better way to handle this, let me know. As a side note, I added you to the CODEOWNERS file for the german language files, so assuming I did that right you shouldn't need my review on any changes that just modify those files.

**Comment by BuzZoiDk24** [comment]
Added them successfully. 👍  I guess that's the best way to do it.
