### ISSUE TITLE
Add feature to allow Dane’s age of exploration

### ISSUE THREAD

**Issue by m007368** [ti-assistant/issues#38]
Request functionality to add new systems on edge of board  as part of “Age of exploration” “expansion.”

**Comment by SephHawkins** [comment]
Added in.

- During setup, the Age of Exploration scenario can be selected in the Options menu.
- Once selected, the ability is available on a player's turn under Components -> Techs -> Age of Exploration, if that player currently owns Dark Energy Tap.
- Selecting Age of Exploration allows a player to add an unused tile to any open spot adjacent to another system.
