### ISSUE TITLE
Allow non player home systems on map for “minor species” “expansion”.

### ISSUE THREAD

**Issue by m007368** [ti-assistant/issues#39]
Request ability to place non player home systems as minor species on “X/twitter”.

https://x.com/CreussEmissary/status/1792421868885959064

**Comment by SephHawkins** [comment]
Added in.

- The [Map Builder](https://ti-assistant.com/map-builder) now includes the home systems in the available tiles.
- Any home systems that are part of the map string will have their planets included and their types set to all three (Cultural, Hazardous, and Industrial).

The assistant doesn't currently track alliances in any way, but if I add that in I'll be sure to update it to grant players the correct commander abilities.
