### ISSUE TITLE
Unable to See Objectives on Mobile when clicking under "Faction Details"

### ISSUE THREAD

**Issue by Lufcyad** [ti-assistant/issues#41]
When I click on objectives and try to view more information it shows the objective name with the description above. The description is cut off and can't be scrolled.

**Comment by Lufcyad** [comment]
The occurs with tech descriptions as well

**Comment by SephHawkins** [comment]
Hey there - thanks for the bug report. I can't seem to reproduce this though - could you let me know what browser you are using and whether this is on iOS or Android?

**Comment by Lufcyad** [comment]
ios. And this is in chrome or safari. I've attached a screenshot. 

![image](https://github.com/ti-assistant/issues/assets/48143758/b40568fe-a006-455e-b10f-aa23ce585597)

**Comment by SephHawkins** [comment]
Thanks for the screenshot - that's very helpful. I'll take a pass on fixing this.

**Comment by SephHawkins** [comment]
Ok - I believe that this should now be fixed. I tested via an iOS emulator though, so it's possible that it's still an issue - if so, feel free to reopen this.
