### ISSUE TITLE
5 Player Map String Rendering Errors

### ISSUE THREAD

**Issue by geobig** [ti-assistant/issues#42]
When I attempt to load this 5 player map string for a new game (86A3 78 28 48 26 72 67 87A3 75 65 79 76 64 31 69 66 29 88A3 85A3 84A3 37 0 40 62 0 35 42 0 34 49 0 44 46 0 39 83A3) the system tiles on the left and right shoulders of the map are duplicated, so two identical system tiles on the left shoulder and two identical system tiles on the right shoulder, tried multiple times and it comes out the same.

Yet if I go directly to the map builder via the start menu there are no issues with this map string being rendered.

**Comment by SephHawkins** [comment]
Hi there - thanks for reporting this issue. I'm having some trouble reproducing the error though, when I put that map string in for a 5 player game it displays correctly. 

Could you provide a screenshot of the error?

**Comment by SephHawkins** [comment]
This is likely the same issue as #51. Closing this in favor of the other one.
