### ISSUE TITLE
Support for milty draft 

### ISSUE THREAD

**Issue by vict0370** [ti-assistant/issues#71]
Hey 

Would it be possible to add the feature to support the map setup for the milty draft 8p game? 

I have attached a photo of it. 

I wanna thank you for this awesome tool. Me and my play group really apreciate it! 

![image](https://github.com/user-attachments/assets/2ae0c76e-d4f5-40d0-a4b3-e576741e95e9)

**Comment by SephHawkins** [comment]
Hi there - thanks for reporting this. That looks like the 8 player Warp map - if it is, TI Assistant already supports it.

On the Setup Page, you just need to select the Warp Map Style, and then put in the Map String.
![Screenshot 2024-12-14 231720](https://github.com/user-attachments/assets/e84faea6-2207-4eaf-8470-5aaeb63e1386)
