### ISSUE TITLE
Bug: Strategy phase picks seem to glitch at times

### ISSUE THREAD

**Issue by signoreliro** [ti-assistant/issues#8]
Here, for instance, Naaz-Rokha can still pick despite already having picked Trade:
![image](https://github.com/ti-assistant/issues/assets/80068049/0ebf1679-d3a0-42cd-91a5-1c203d80e2bb)

Or here, where both Xxcha and Council Keleres were skipped: 
![image](https://github.com/ti-assistant/issues/assets/80068049/7d340f0e-6201-464c-a472-e377a073508d)

While the last 2 can be reset with the 'reset phase' button, sometimes the 'reset phase' and 'undo sc pick' buttons disappear and the only button remaining is the 'advance to action phase' despite not all players having picked. This results in the action phase not including all players. Seems to be rare, but has happened twice. Don't know how to replicate. 

All these might have something to do with a slight difference in timing between when promoting the 'on deck' player to active and promoting the next player to 'on deck'. I believe clicking the choices slower can alleviate these issues.

**Comment by SephHawkins** [comment]
Oof, yeah - this has been a thorn in my side for a while.

I think I've resolved it on the staging site. The inconsistent nature of it makes it tricky to say for certain that it's fixed though.
